# Generated by rspec-sinatra. (2015-08-24 10:06:44 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'lib/app.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'factory_girl'
require_relative 'helpers/session_helpers'
require_relative 'helpers/task_helpers'
require 'database_cleaner'

Capybara.app = VirtualAssistant::App
RSpec.configure do |config|
  config.include SessionHelpers
  config.include TaskHelpers

  config.include Capybara::DSL
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.include FactoryGirl::Syntax::Methods

  FactoryGirl.definition_file_paths = %w{./spec/factories}
  FactoryGirl.find_definitions

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end
